### ISSUE TITLE
Plugin does not work with cordova-android@7.0.0

### ISSUE THREAD

**Issue by Ritzlgrmft** [koenoe/cordova-disable-http-cache#1]
Error message is 

```
Installing "cordova-disable-http-cache" for android
Failed to install 'cordova-disable-http-cache': Error: ENOENT: no such file or directory, open '...\platforms\android\AndroidManifest.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.readFileSync (fs.js:509:33)
    at Object.parseElementtreeSync (...\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (...\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (...\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (...\platforms\android\cordova\Api.js:223:57)
    at handleInstall (...\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (...\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
(node:36368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '...\platforms\android\AndroidManifest.xml'
```

This happens, since cordova-android@7.0.0 uses a different folder layout, the manifest is now in `...\platforms\Android\app\src\main\AndroidManifest.xml`.

**Comment by koenoe** [comment]
Thanks for your report!
We're still on 6.3.0, but I'll solve this issue as soon as we update to 7.0.0 too.
